### ISSUE TITLE
can´t install the plugin on redmine v2.5.2

### ISSUE THREAD

**Issue by Henry31** [luisfontes19/redmine_stats#1]
Hey,

after adding the plugin to the redmine plugin folder, i don´t see the plugin in the redmine backend.

So i tried to do the plugin migration (you say i don´t need this in the readme) 
``` rake redmine:plugins:migrate RAILS_ENV=production ```

But i get this error:
```
rake aborted!
/usr/share/redmine/plugins/redmine_stats/init.rb:21: syntax error, unexpected tSYMBEG, expecting kDO or '{' or '('
...cess_statistics, nil, {global:true})
                              ^
/usr/share/redmine/plugins/redmine_stats/init.rb:21: syntax error, unexpected ')', expecting kEND
...tatistics, nil, {global:true})
                              ^

Tasks: TOP => redmine:plugins:migrate => environment
```

This also happend if i restart the apache service i will get the same error from "Phusion Passenger".

Can you help me?

---
Environment:
  Redmine version                2.5.2.stable
  Ruby version                   1.8.7-p249 (2010-01-10) [i486-linux]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               MySQL

**Comment by luisfontes19** [comment]
Hello Henry, I think that the problem is related with the hash syntax that I am using, that is only available with versions of ruby >= 1.9. 

I will try to update the code to be compatible with older versions, like yours, as soon as possible, maybe today

**Comment by luisfontes19** [comment]
Can you please check if the problem was solved with the new changes?

I couldn't test it, because I cannot install ruby on the machine that I'm using at the moment.

**Comment by Henry31** [comment]
oh nooo! I read your message on the phone and now i update the ruby version! because our live system has a newer ruby version also. 

Only my test-system is running on this old ruby version. So i decided to update this!

I´m very sorry that you have wasted time with this for me :(

**Comment by luisfontes19** [comment]
No problem, I should thought on that before...

So, was your issue solved?

**Comment by luisfontes19** [comment]
closed for inactivity
