### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by mmiat** [luisfontes19/redmine_stats#43]
redmine 3.4.3
stats plugin 0.0.3

> Started GET "/global_stats/current_week" for 192.168.10.30 at 2017-11-08 10:55:16 +0100
Processing by StatsController#index as HTML
  Parameters: {"time_filter"=>"current_week"}
  Current user: miatello.mauro (id=47)
  Rendered plugins/redmine_stats/app/views/stats/_simple.html.erb (30.2ms)
  Rendered plugins/redmine_stats/app/views/stats/_simple.html.erb (45.0ms)
  Rendered plugins/redmine_stats/app/views/stats/index.html.erb within layouts/base (97.5ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.6ms)

**Comment by mmiat** [comment]
solved with downloading the file _list_simple.html.erb from an older version and putting it to $REDMINE_ROOT/app/views/issues/

**Comment by chopeta** [comment]
Thanks for the fix!
