### ISSUE TITLE
Couldn't find User 

### ISSUE THREAD

**Issue by skibinstein** [luisfontes19/redmine_stats#5]
I have the latest versions (cd202d7). My environment loks like:

Environment:
  Redmine version                2.6.0.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Cvs                            1.12.12
  Git                            1.7.12.4
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.9
  redmine_agile                  1.3.5
  redmine_checklists             3.0.2
  redmine_didyoumean             1.2.0
  redmine_issue_statistics       0.0.1
  redmine_ldap_sync              2.0.4
  redmine_lightbox2              0.1.2
  redmine_people                 0.1.8
  redmine_questions              0.0.5
  redmine_stats                  0.0.2
  redmine_tags                   2.0.1-dev
  redmine_theme_changer          0.1.0
  redmine_watcher_groups         0.0.2
  redmine_wysiwyg                1.0.0

I was trying to access statistics for all projects and redmine returned "Page not found". In logs I have:

Processing by StatsController#index as HTML
  Parameters: {"project"=>"all_projects", "time_filter"=>"last_month"}
  Current user: hubert.skibinski (id=234)
Completed 404 Not Found in 247.9ms

ActiveRecord::RecordNotFound (Couldn't find User with id=277 [WHERE `users`.`type` IN ('User', 'AnonymousUser')]):

User with id=277 exists and it is group. If I remove this group then statistics work.

**Comment by luisfontes19** [comment]
Can you give me the full log of the error?

**Comment by skibinstein** [comment]
Here you are.

Started GET "/stats/last_month?project=all_projects" for 127.0.0.1 at 2015-02-10 14:11:09 +0000
Processing by StatsController#index as HTML
  Parameters: {"project"=>"all_projects", "time_filter"=>"last_month"}
  Current user:  (id=234)
Completed 404 Not Found in 247.9ms

ActiveRecord::RecordNotFound (Couldn't find User with id=277 [WHERE `users`.`type` IN ('User', 'AnonymousUser')]):
  activerecord (3.2.19) lib/active_record/relation/finder_methods.rb:344:in `find_one'
  activerecord (3.2.19) lib/active_record/relation/finder_methods.rb:315:in `find_with_ids'
  activerecord (3.2.19) lib/active_record/relation/finder_methods.rb:107:in `find'
  activerecord (3.2.19) lib/active_record/querying.rb:5:in `find'
  plugins/redmine_stats/app/controllers/stats_controller.rb:37:in `block in index'
  plugins/redmine_stats/app/controllers/stats_controller.rb:37:in `map'
  plugins/redmine_stats/app/controllers/stats_controller.rb:37:in `index'
  actionpack (3.2.19) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.19) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.19) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.19) lib/active_support/callbacks.rb:491:in `_run__2569340057430041223__process_action__3059262783978275032__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.19) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.19) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.19) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.19) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.19) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.19) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.19) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.19) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.19) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `_run__2037069968561810177__call__151330911178342282__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.19) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.19) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.19) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.19) lib/rails/engine.rb:484:in `call'
  railties (3.2.19) lib/rails/application.rb:231:in `call'
  railties (3.2.19) lib/rails/railtie/configurable.rb:30:in `method_missing'
  unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
  unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
  unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
  unicorn (4.8.3) lib/unicorn/http_server.rb:140:in `start'
  unicorn (4.8.3) bin/unicorn:126:in `<top (required)>'
  /home/redmine/.rvm/gems/ruby-2.1.5/bin/unicorn:23:in `load'
  /home/redmine/.rvm/gems/ruby-2.1.5/bin/unicorn:23:in `<main>'
  /home/redmine/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
  /home/redmine/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

**Comment by luisfontes19** [comment]
I've reproduced your bug and fixed it, but it is possible that you'll find another one related to. If so let me know
