### ISSUE TITLE
Author table does not work 

### ISSUE THREAD

**Issue by skibinstein** [luisfontes19/redmine_stats#6]
When I try display statistics author table does not work. 

![author](https://cloud.githubusercontent.com/assets/10942661/6150457/812c17aa-b207-11e4-9fb8-afc4f497fdfb.jpg)

Unfortunately I don't have any errors in logs

Completed 200 OK in 454.3ms (Views: 198.6ms | ActiveRecord: 124.9ms)
Started GET "/stats/last_month?project=infrastructure" for 127.0.0.1 at 2015-02-11 15:48:18 +0000
Processing by StatsController#index as HTML
  Parameters: {"project"=>"infrastructure", "time_filter"=>"last_month"}
  Current user:  (id=234)
  Rendered plugins/redmine_stats/app/views/stats/_simple.html.erb (7.4ms)
  Rendered plugins/redmine_stats/app/views/stats/_simple.html.erb (30.6ms)
  Rendered issues/_list_simple.html.erb (27.5ms)
  Rendered plugins/redmine_stats/app/views/stats/_simple.html.erb (9.5ms)
  Rendered plugins/redmine_stats/app/views/stats/_simple.html.erb (2.8ms)
  Rendered plugins/redmine_stats/app/views/stats/_sidebar.html.erb (14.6ms)
  Rendered plugins/redmine_stats/app/views/stats/index.html.erb within layouts/base (101.6ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.9ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (4.1ms)
Completed 200 OK in 390.7ms (Views: 152.8ms | ActiveRecord: 126.1ms)

**Comment by skibinstein** [comment]
Thank you very much. 
I think you should add this plugin to www.redmine.org/plugins.
That are the most useful redmine statistics I've seen.

**Comment by luisfontes19** [comment]
Thank you very much for your comment.

Well, the plugin is already in the redmine plugins section
http://www.redmine.org/plugins/redmine_stats


If you have any suggestion to the plugin just let me know, I've developed it with a really short time  (this means messy code) for a company that knew what they wanted, but now it can grow and have new indicators

**Comment by skibinstein** [comment]
Hi Luis

I think the most useful feature you could add is a custom time interval.
Right now we are limited to last and current week/month.

Hubert

2015-02-11 17:34 GMT+00:00 Luis Fontes <notifications@github.com>:
