### ISSUE TITLE
file structure problem (tabs instead spaces)

### ISSUE THREAD

**Issue by dorogarcia** [luisfontes19/redmine_stats#8]
Hello,

I am testing the last version of your plugin with clean install of redmine 2.6.2 and i get a lot of errors. After fix this file (align with spaces and add text between ""):

plugins/redmine_stats/config/locales/en.yml

# English strings go here for Rails i18n
en:
  stats_label_stats:                                "Statistics"
  stats_label_issue_activity:                       "Issue Activity"
  stats_label_new_issues_priorities:                "New Issue Priorities"
  stats_label_more_active_issues:                   "More active issues"
  stats_label_filters:                              "Filters"
  stats_label_current_week:                         "Current Week"
  stats_label_current_month:                        "Current Month"
  stats_label_last_week:                            "Last Week"
  stats_label_last_month:                           "Last Month"
  stats_label_begining_of_time:                     "Since Beginning of Time"
  stats_label_filtering_between:                    "Filtering betwween: "
  stats_label_and:                                  "and"
  stats_label_open_issues_count:                    "Currently Opened Issues: "
  stats_all_projects:                               "All Projects"
  stats_label_open_issues:                          "Open Issues"
  stats_label_closed_issues:                        "Closed Issues"
  stats_label_legend:                               "Legend"
  stats_open_issues_chart_info:                     "Total opened issues since beginning of time, no filters"

I have new errors:

Started GET "/stats/current_week" for XX.XX.XX.XX at Thu Feb 26 11:10:40 +0100 2015
Processing by StatsController#index as HTML
  Parameters: {"time_filter"=>"current_week"}
  Current user: admin (id=1)
  Rendered plugins/redmine_stats/app/views/stats/_simple.html.erb (4.4ms)
  Rendered plugins/redmine_stats/app/views/stats/_simple.html.erb (1.8ms)
  Rendered issues/_list_simple.html.erb (27.5ms)
  Rendered plugins/redmine_stats/app/views/stats/_simple.html.erb (3.7ms)
  Rendered plugins/redmine_stats/app/views/stats/_simple.html.erb (1.9ms)
  Rendered plugins/redmine_stats/app/views/stats/_sidebar.html.erb (1.7ms)
  Rendered plugins/redmine_stats/app/views/stats/index.html.erb within layouts/base (52.8ms)
Completed 500 Internal Server Error in 225.9ms

ActionView::Template::Error (compile error
/var/www/redmine/plugins/redmine_stats/app/views/stats/_sidebar.html.erb:21: syntax error, unexpected ':'
...of_time), "redirect(0)",class: ("selected" if params["time_f...
                              ^
/var/www/redmine/plugins/redmine_stats/app/views/stats/_sidebar.html.erb:22: syntax error, unexpected ':'
...nt_week), "redirect(1)",class: ("selected" if params["time_f...
                              ^
/var/www/redmine/plugins/redmine_stats/app/views/stats/_sidebar.html.erb:23: syntax error, unexpected ':'
...st_week), "redirect(2)",class: ("selected" if params["time_f...
                              ^
/var/www/redmine/plugins/redmine_stats/app/views/stats/_sidebar.html.erb:24: syntax error, unexpected ':'
...t_month), "redirect(3)",class: ("selected" if params["time_f...
                              ^
/var/www/redmine/plugins/redmine_stats/app/views/stats/_sidebar.html.erb:25: syntax error, unexpected ':'
...t_month), "redirect(4)",class: ("selected" if params["time_f...
                              ^
/var/www/redmine/plugins/redmine_stats/app/views/stats/_sidebar.html.erb:35: syntax error, unexpected kDO_BLOCK, expecting kEND
			@projects.each do |p| projects_tmp << p end
			                 ^
/var/www/redmine/plugins/redmine_stats/app/views/stats/_sidebar.html.erb:86: syntax error, unexpected kENSURE, expecting $end):
    18:
    19:
    20: <div>
    21: 	<%=link_to_function l(:stats_label_begining_of_time), "redirect(0)",class: ("selected" if params["time_filter"] == "all" || params["time_filter"].nil?) %><br>
    22: 	<%=link_to_function l(:stats_label_current_week), "redirect(1)",class: ("selected" if params["time_filter"] == "current_week") %><br>
    23: 	<%=link_to_function l(:stats_label_last_week), "redirect(2)",class: ("selected" if params["time_filter"] == "last_week") %><br>
    24: 	<%=link_to_function l(:stats_label_current_month), "redirect(3)",class: ("selected" if params["time_filter"] == "current_month") %><br>
  plugins/redmine_stats/app/views/stats/_sidebar.html.erb:86:in `compile'

**Comment by luisfontes19** [comment]
Which ruby version are you using?
This plugin is intended to be used with  ruby 2.1 or higher... 
It seems to me that you have a problem with syntax implemented in recent ruby versions...
Anyway I'll change the code that to be compatible

**Comment by dorogarcia** [comment]
Argggg!!! This is the problem, i am so sorry if i disturbed you:

root@lab:...# dpkg -l|grep ruby
ii  librack-ruby                                   1.3.5-1                                             Transitional package for ruby-rack
ii  libruby                                        4.8                                                 Transitional package for libruby1.8
ii  libruby1.8                                     1.8.7.352-2ubuntu1.6                                Libraries necessary to run Ruby 1.8
ii  ruby                                           4.8                                                 Transitional package for ruby1.8
ii  ruby-dev                                       4.8                                                 Transitional package for ruby1.8-dev
ii  ruby-rack                                      1.3.5-1                                             Modular Ruby webserver interface
ii  ruby1.8                                        1.8.7.352-2ubuntu1.6                                Interpreter of object-oriented scripting language Ruby 1.8
ii  ruby1.8-dev                                    1.8.7.352-2ubuntu1.6                                Header files for compiling extension modules for the Ruby 1.8
ii  rubygems                                       1.8.15-1ubuntu0.1                                   package management framework for Ruby libraries/applications
root@lab:...#

**Comment by luisfontes19** [comment]
No problem, anyway I've changed the code in the file that you were having problems (redmine_stats/app/views/stats/_sidebar.html.erb) in commit [c2894d4](https://github.com/luisfontes19/redmine_stats/commit/c2894d4aa1353afe54a5d029a959d0c48eb63fb2)

I've already done this... but seems that I've missed this file...

**Comment by dorogarcia** [comment]
Hello,

If you fix this file: plugins/redmine_stats/config/locales/en.yml. It works (i will continuous testing your plugin)

Thanks.

# English strings go here for Rails i18n
en:
  stats_label_stats:                                "Statistics"
  stats_label_issue_activity:                       "Issue Activity"
  stats_label_new_issues_priorities:                "New Issue Priorities"
  stats_label_more_active_issues:                   "More active issues"
  stats_label_filters:                              "Filters"
  stats_label_current_week:                         "Current Week"
  stats_label_current_month:                        "Current Month"
  stats_label_last_week:                            "Last Week"
  stats_label_last_month:                           "Last Month"
  stats_label_begining_of_time:                     "Since Beginning of Time"
  stats_label_filtering_between:                    "Filtering betwween: "
  stats_label_and:                                  "and"
  stats_label_open_issues_count:                    "Currently Opened Issues: "
  stats_all_projects:                               "All Projects"
  stats_label_open_issues:                          "Open Issues"
  stats_label_closed_issues:                        "Closed Issues"
  stats_label_legend:                               "Legend"
  stats_open_issues_chart_info:                     "Total opened issues since beginning of time, no filters"

**Comment by luisfontes19** [comment]
that file should not be a problem, tabs or spaces have no problem, and the quotes are optional. I'll try to understand why it does not work with you

**Comment by dorogarcia** [comment]
The quotes are not the problem, the problem are the tab + spaces, i removed all of them and just add spaces and quotes, but as you say, quotes are not important.
